### ISSUE TITLE
Error al importar KML

### ISSUE THREAD

**Issue by deabelle2** [mapbiomasar/relevator-tools#1]
Al importar un archivo KML aparece el error: Alert. Error al importar el archivo. Desde una tablet Samsung Galaxy Tab A.

**Comment by ahMarrone** [comment]
Hola.

Si el archiv .kml es correcto, quizás el error pueda ser un tema de permisos. Si levantás un archivo .kml que esté ubicado en el directorio raíz en donde se ubica el proyecto (/Android/data/io.inta.mapbiomas/), tenés el mismo problema?

De todas formas, la aplicación debería preguntar si se le permite el acceso de lectura en cualquier parte del filesystem. Pero vamos descartando por partes.
